---
- name: install extensions
  become: yes
  become_user: "{{ item.0.username }}"
  command: "code --install-extension '{{ item.1 }}'"
  with_subelements:
    - "{{ users }}"
    - visual_studio_code_extensions
    - skip_missing: yes
  register: vscode_install_result
  changed_when: "'already installed' not in vscode_install_result.stdout"
